### ISSUE TITLE
Fatal error following upgrade to 2.19.0

### ISSUE THREAD

**Issue by totallyben** [laminas/laminas-navigation#52]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 2.19.0

#### Summary

After upgrading to 2.19.0 we are seeing the error:

```
NOTICE: PHP message: PHP Fatal error:  Uncaught ReflectionException: Cannot access non-public property Laminas\View\HelperPluginManager::$creationContext in /app/vendor/laminas/laminas-navigation/src/View/HelperConfig.php:159
```

The issue is related to `$r->setAccessible(true);` being removed from `HelperConfig::getParentContainer()` line 159.

We are running php 8.0:

```
PHP 8.0.30 (cli) (built: Nov  1 2023 07:03:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.30, Copyright (c) Zend Technologies
```

Rolling back to the previous version or adding that line back in resolves the issue.

**Comment by Ocramius** [comment]
`laminas/laminas-navigation:2.19.0` requires PHP 8.1.0 at minimum.

https://github.com/laminas/laminas-navigation/blob/478d487203a59588597233b3f62102121a060a0b/composer.json#L34
